### ISSUE TITLE
OutOfRangeError

### ISSUE THREAD

**Issue by handsomefengfeng** [DetectionTeamUCAS/Cascade-RCNN_Tensorflow#4]
The first problem i met was that i could't convert the data to tfrecord. Using the code convert_data_to_tfrecord.py  always had the pascal_train.tfrecord to be 0KB. And i ensured that i have made the --config to be right. So i refered to the create_pascal_tf_record.py at Tensorflow's github and obtained the pascal_train.tfrecord with 209.61MB. I'm wondering if there is anything inappropriate so that it would result in any mistakes?

After obtaining the  pascal_train.tfrecord, I started to train by
`python train.py`

Then , the logs:
`Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train()
  File "train.py", line 165, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

Caused by op 'get_batch/batch', defined at:
  File "train.py", line 185, in <module>
    train()
  File "train.py", line 33, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 98, in next_batch
    dynamic_pad=True)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 919, in batch
    name=name)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 716, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 946, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]`

Thanks.

**Comment by Ellen4168** [comment]
hello，Can you tell me how you solved the problem
